### ISSUE TITLE
How to do nested views?

### ISSUE THREAD

**Issue by ln-12** [ihorvovk/Routing-in-SwiftUI-with-type-erased-modifiers#1]
Hey, awesome approach! I am wondering how I would use this project for nested navigation. Let's say for example I have the `PresentingView` which navigates to the `PresentedView` which then navigates to a `DetailPresentedView`. And how could I decide if I want to navigate back one screen or to the root?

**Comment by ihorvovk** [comment]
Hey, thank you! You need to have routers for all those views: PresentingRouter, PresentedRouter, DetailPresentedRouter. Then you can add the necessary logic to those routers. For example, you can initialise a router with an onDismiss closure and overwrite the dismiss function calling the closure at the end. This will allow to decide how far to return back depending on presenting context. But you will need to dismiss screens one by one with a 0.3 seconds delay. I haven't found how to dismiss a few screens at once without such a consecutive effect with the current SDK. Hope it will be possible with the next update of SwiftUI.

**Comment by ln-12** [comment]
Well, it doesn't sound like an optimal solution, but I'll give it a try. Thanks a lot!
